//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeaBotGUI {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PrivateLocal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PrivateLocal() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeaBotGUI.PrivateLocal", typeof(PrivateLocal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warning, at least 1 SeaBot user got banned for using interval, which is lower than 12..
        /// </summary>
        internal static string BARREL_INTERVAL_WARNING {
            get {
                return ResourceManager.GetString("BARREL_INTERVAL_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Removed {0} {1}&apos;s.
        /// </summary>
        internal static string INVENTORY_REMOVED {
            get {
                return ResourceManager.GetString("INVENTORY_REMOVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By clicking &apos;OK&apos; you agree that neither the program nor the developer is responsible for your account.
        ///In order not to get a ban, please do not use too small a number in the intervals of the barrel or just do not use them..
        /// </summary>
        internal static string SEABOTGUI_WELCOME {
            get {
                return ResourceManager.GetString("SEABOTGUI_WELCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No telegram token.
        /// </summary>
        internal static string TELEGRAM_NO_TOKEN {
            get {
                return ResourceManager.GetString("TELEGRAM_NO_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Empty server_token
        ///Please fill server token in Settings tab.
        /// </summary>
        internal static string TOKEN_EMPTY {
            get {
                return ResourceManager.GetString("TOKEN_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [Current] Version: {0}.
        /// </summary>
        internal static string VERSION_CURRENT {
            get {
                return ResourceManager.GetString("VERSION_CURRENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [Old] Version: {0}.
        /// </summary>
        internal static string VERSION_OLD {
            get {
                return ResourceManager.GetString("VERSION_OLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A new update has been released, press OK to open download page!.
        /// </summary>
        internal static string VERSION_UPDATE_MBOX {
            get {
                return ResourceManager.GetString("VERSION_UPDATE_MBOX", resourceCulture);
            }
        }
    }
}
