// SeaBotCore
// Copyright (C) 2018 Weespin
// 
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

using System.Diagnostics.CodeAnalysis;

namespace SeaBotCore
{
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    public static class Enums
    {
        public enum EFactoryType
        {
            SteelFactory = 4,
            Stone = 5,
            Saw = 3,
            BigSteel = 15,
            BigStone = 14,
            BigSaw = 13,
            Machinery = 11
        }

        public enum EMaterial
        {
            Coins = 1,
            Gems = 2,
            Fish = 3,
            Wood = 4,
            Stone = 5,
            Iron = 6,
            Cocoa = 7,
            Tea = 8,
            Cloth = 9,
            PirateHat = 10,
            CannonBalls = 11,
            SilverSkull = 12,
            GoldenSkull = 13,
            GrapeVine = 14,
            Shield = 15,
            SilverChest = 16,
            GoldenChest = 17,
            Candle = 18,
            Sextant = 19,
            Compass = 20,
            Coffee = 21,
            Lemon = 22,
            Bottle = 23,
            SugarCane = 24,
            Coconut = 25,
            RumBarrel = 26,
            BarrelOfTheBat = 27,
            Pumpkin = 28,
            LostSoul = 29,
            Candy = 30,
            HeartOfSea = 31,
            SoulOfSea = 32,
            MechanicalPart = 33,
            Cinnamon = 34,
            BlackPepper = 35,
            WoodenPony = 36,
            ChristmasTree = 37,
            SantasSock = 38,
            GoldenBell = 39,
            Gingerbread = 40,
            RealDeVellan = 41,
            PesoDeOcho = 42,
            Doubloon = 43,
            Tomato = 44,
            Feather = 45,
            Chocolate = 46,
            Rose = 47,
            Totem = 48,
            Shamrock = 49,
            PotOfGold = 50,
            Horseshoe = 51,
            Bunny = 52,
            Moai = 53,
            Tulip = 54,
            BlueEgg = 55,
            RedEgg = 56,
            Daisy = 57,
            Key = 58,
            LaurelWreath = 59,
            RomanSandals = 60,
            Figs = 61,
            GoldenEagle = 62,
            Amphora = 63,
            Olives = 64,
            Rice = 65,
            Sake = 66,
            Katana = 67,
            Sakura = 68,
            Mon = 69,
            Koban = 70,
            SummerCocktail = 72,
            Experience = 73,
            Sailors = 74,
            Banana = 75,
            BottleOfBooze = 76,
            PiratePistol = 77,
            Parrot = 78,
            GoldenTooth = 79,
            WhitePearl = 80,
            BlackPearl = 81,
            SewingKit = 82,
            BodyPart = 83,
            Electrode = 84,
            Nails = 85,
            Watch = 86,
            MechanicalHeart = 87,
            Rope = 88,
            Anchor = 89,
            SeaportLogo = 90,
            Gloves = 91,
            Eggnog = 92,
            Sledge = 93,
            Lantern = 94,
            ChristmasStar = 95,
            Snowflake = 96,
            Krill = 97,
            Notebook = 98,
            PenguinEgg = 99,
            Bamboo = 100,
            Silk = 101,
            Gunpowder = 102,
            Porcelain = 103,
            JadeDragon = 104,
            TeaLeaves = 105,
            ChineseLantern = 106,
            Balloon = 107,
            CannedSpinach = 108,
            Barbell = 109,
            Pipe = 110,
            CaptainsCap = 111,
            Rudder = 112,
            SpinachLeaves = 113,
            ShipScrew = 114,
            SilverCutlery = 115,
            Lifebuoy = 116,
            TitanicTicket = 117,
            HeartOfTheSea = 118,
            Flare = 119,
            Monocle = 120,
            Ink = 121,
            PocketWatch = 122,
            Suitcase = 123,
            Books = 124,
            Globe = 125,
            Pen = 126,
            GeologyKit = 127,
            Fossil = 128,
            Amber = 129,
            Fieldnotes = 130,
            Seashell = 131,
            Tortoise = 132,
            WineAmphora = 133,
            Lyre = 134,
            Helmet = 135,
            Trident = 136,
            BowOfApollo = 137,
            BlackOlives = 138,
            Mask = 139,
            Drachma = 140,
            Vizsla = 141,
            RazorBlade = 142,
            Wig = 143,
            Suspenders = 144,
            Cards = 145,
            StrawHat = 146,
            Frog = 147,
            Sardine = 148,
            Octopus = 149,
            Crab = 150,
            LegendaryTuna = 151,
            PufferFish = 152,
            Mirror = 153,
            WoodenStake = 154,
            BloodyMary = 155,
            Garlic = 156,
            SignetRing = 157,
            Bat = 158,
            BlackCat = 159,
            CrewToken = 160,
            CapacityToken = 161,
            Peanuts = 162,
            PeanutOil = 163,
            Cake = 164,
            CandyCane = 165,
            Scarf = 166,
            TeddyBear = 167,
            Ornament = 168,
            Mistletoe = 169,
            Reindeer = 170,
            Oil = 171,
            Fuel = 172,
            Cement = 173,
            Concrete = 174
        }

        public enum EObject
        {
            achievement,
            building,
            construction_site,
            boat,
            boatCargo,
            ship,
            shipCargo,
            hometown,contractor,marketplace,
            outpost,
            social_contract,
            upgradeable,
            wreck,
            dealer,
            global_contractor,
            crossroad,
            material,
            buildArea,
            levelUp,
            xp,
            sailor,
            product,
            @event,
            barrel,
            museum_ship,
            museum_level,
            captain,
            gift,
            treasure,
            vintage_offer,
            merchant_offer,
            items_offer,
            items_offerCargo,
            lost_treasure,
            personal_guide,
            quest_line,
            captain_new_rarity,
            equation,
            videoreward

        }
    }
}