//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeaBotCore {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeaBotCore.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;levels&gt;
        ///      &lt;level id=&quot;1&quot;&gt;
        ///        &lt;id&gt;1&lt;/id&gt;
        ///        &lt;mass&gt;3&lt;/mass&gt;
        ///        &lt;turn_count&gt;12&lt;/turn_count&gt;
        ///        &lt;turn_time&gt;20&lt;/turn_time&gt;
        ///        &lt;output_id&gt;3&lt;/output_id&gt;
        ///        &lt;output_amount&gt;4&lt;/output_amount&gt;
        ///        &lt;model_name&gt;Fisherman_01&lt;/model_name&gt;
        ///      &lt;/level&gt;
        ///      &lt;level id=&quot;2&quot;&gt;
        ///        &lt;id&gt;2&lt;/id&gt;
        ///        &lt;mass&gt;3&lt;/mass&gt;
        ///        &lt;turn_count&gt;24&lt;/turn_count&gt;
        ///        &lt;turn_time&gt;20&lt;/turn_time&gt;
        ///        &lt;output_id&gt;3&lt;/output_id&gt;
        ///        &lt;output_amount&gt;4&lt;/output_amount&gt;
        ///        &lt;mo [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string BoatDefenitions {
            get {
                return ResourceManager.GetString("BoatDefenitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {&quot;items&quot;:{&quot;item&quot;:[{&quot;def_id&quot;:0,&quot;version_id&quot;:1,&quot;name&quot;:&quot;Default&quot;,&quot;name_loc&quot;:&quot;&quot;,&quot;desc_loc&quot;:&quot;&quot;,&quot;tile_width&quot;:0,&quot;tile_height&quot;:0,&quot;on_grid&quot;:1,&quot;type&quot;:&quot;generic&quot;,&quot;max_level&quot;:1,&quot;hide&quot;:0,&quot;upgrade_priority&quot;:0,&quot;levels&quot;:{&quot;level&quot;:[{&quot;id&quot;:0,&quot;req_type&quot;:&quot;&quot;,&quot;req_id&quot;:0,&quot;req_level&quot;:0,&quot;player_level&quot;:0,&quot;player_level_gem&quot;:0,&quot;xp&quot;:0,&quot;sailors_regen&quot;:0,&quot;sailors_cap&quot;:0,&quot;gem_price&quot;:1000,&quot;gem_upgrade_time&quot;:0,&quot;upgrade_time&quot;:0,&quot;boat_level&quot;:0,&quot;lighthouse_level&quot;:0,&quot;museum_level&quot;:0,&quot;iso_x&quot;:0,&quot;iso_y&quot;:0,&quot;bounds&quot;:&quot;0,0,0,0&quot;,&quot;iso_width&quot;:0,&quot;iso_height&quot; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string BuildingDef {
            get {
                return ResourceManager.GetString("BuildingDef", resourceCulture);
            }
        }
    }
}
