//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeaBotGUI.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PrivateLocal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PrivateLocal() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeaBotGUI.Localization.PrivateLocal", typeof(PrivateLocal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warning, at least 1 SeaBot user got banned for using interval, which is lower than 12..
        /// </summary>
        internal static string BARREL_INTERVAL_WARNING {
            get {
                return ResourceManager.GetString("BARREL_INTERVAL_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Removed {0} {1}&apos;s.
        /// </summary>
        internal static string INVENTORY_REMOVED {
            get {
                return ResourceManager.GetString("INVENTORY_REMOVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на By clicking &apos;OK&apos; you agree that neither the program nor the developer is responsible for your account.
        ///In order not to get a ban, please do not use too small a number in the intervals of the barrel or just do not use them..
        /// </summary>
        internal static string SEABOTGUI_WELCOME {
            get {
                return ResourceManager.GetString("SEABOTGUI_WELCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Social Contract.
        /// </summary>
        internal static string SHIPS_SOCIAL_CONTRACT {
            get {
                return ResourceManager.GetString("SHIPS.SOCIAL_CONTRACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Amount.
        /// </summary>
        internal static string STAT_AMOUNT {
            get {
                return ResourceManager.GetString("STAT_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Coins.
        /// </summary>
        internal static string STAT_COINS {
            get {
                return ResourceManager.GetString("STAT_COINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fish.
        /// </summary>
        internal static string STAT_FISH {
            get {
                return ResourceManager.GetString("STAT_FISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gems.
        /// </summary>
        internal static string STAT_GEMS {
            get {
                return ResourceManager.GetString("STAT_GEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Iron.
        /// </summary>
        internal static string STAT_IRON {
            get {
                return ResourceManager.GetString("STAT_IRON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Level.
        /// </summary>
        internal static string STAT_LEVEL {
            get {
                return ResourceManager.GetString("STAT_LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sailors.
        /// </summary>
        internal static string STAT_SAILORS {
            get {
                return ResourceManager.GetString("STAT_SAILORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stone.
        /// </summary>
        internal static string STAT_STONE {
            get {
                return ResourceManager.GetString("STAT_STONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time.
        /// </summary>
        internal static string STAT_TIME {
            get {
                return ResourceManager.GetString("STAT_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wood.
        /// </summary>
        internal static string STAT_WOOD {
            get {
                return ResourceManager.GetString("STAT_WOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        internal static string TELEGRAM_BTN_ABOUT {
            get {
                return ResourceManager.GetString("TELEGRAM_BTN_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AutoShip strategy.
        /// </summary>
        internal static string TELEGRAM_BTN_AUTOSHIP_OPTIMAL {
            get {
                return ResourceManager.GetString("TELEGRAM_BTN_AUTOSHIP_OPTIMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Barrels.
        /// </summary>
        internal static string TELEGRAM_BTN_BARRELS {
            get {
                return ResourceManager.GetString("TELEGRAM_BTN_BARRELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hibernation.
        /// </summary>
        internal static string TELEGRAM_BTN_HIBERNATION {
            get {
                return ResourceManager.GetString("TELEGRAM_BTN_HIBERNATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Intervals.
        /// </summary>
        internal static string TELEGRAM_BTN_INTERVALS {
            get {
                return ResourceManager.GetString("TELEGRAM_BTN_INTERVALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Inventory.
        /// </summary>
        internal static string TELEGRAM_BTN_INVENTORY {
            get {
                return ResourceManager.GetString("TELEGRAM_BTN_INVENTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Iron.
        /// </summary>
        internal static string TELEGRAM_BTN_IRON {
            get {
                return ResourceManager.GetString("TELEGRAM_BTN_IRON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Limits.
        /// </summary>
        internal static string TELEGRAM_BTN_LIMITS {
            get {
                return ResourceManager.GetString("TELEGRAM_BTN_LIMITS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Main.
        /// </summary>
        internal static string TELEGRAM_BTN_MAIN {
            get {
                return ResourceManager.GetString("TELEGRAM_BTN_MAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Menu.
        /// </summary>
        internal static string TELEGRAM_BTN_MENU {
            get {
                return ResourceManager.GetString("TELEGRAM_BTN_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string TELEGRAM_BTN_SETTINGS {
            get {
                return ResourceManager.GetString("TELEGRAM_BTN_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ships.
        /// </summary>
        internal static string TELEGRAM_BTN_SHIPS {
            get {
                return ResourceManager.GetString("TELEGRAM_BTN_SHIPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start.
        /// </summary>
        internal static string TELEGRAM_BTN_START {
            get {
                return ResourceManager.GetString("TELEGRAM_BTN_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stone.
        /// </summary>
        internal static string TELEGRAM_BTN_STONE {
            get {
                return ResourceManager.GetString("TELEGRAM_BTN_STONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stop.
        /// </summary>
        internal static string TELEGRAM_BTN_STOP {
            get {
                return ResourceManager.GetString("TELEGRAM_BTN_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AutoShip material.
        /// </summary>
        internal static string TELEGRAM_BTN_STOP_AUTOSHIP_MATERIAL {
            get {
                return ResourceManager.GetString("TELEGRAM_BTN_STOP_AUTOSHIP_MATERIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Strategy.
        /// </summary>
        internal static string TELEGRAM_BTN_STRATEGY {
            get {
                return ResourceManager.GetString("TELEGRAM_BTN_STRATEGY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wood.
        /// </summary>
        internal static string TELEGRAM_BTN_WOOD {
            get {
                return ResourceManager.GetString("TELEGRAM_BTN_WOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на But the bot is not running.
        /// </summary>
        internal static string TELEGRAM_ERR_BOT_NOT_RUNNING {
            get {
                return ResourceManager.GetString("TELEGRAM_ERR_BOT_NOT_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на But the bot is already running.
        /// </summary>
        internal static string TELEGRAM_ERR_BOT_RUNNING {
            get {
                return ResourceManager.GetString("TELEGRAM_ERR_BOT_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can&apos;t parse string!.
        /// </summary>
        internal static string TELEGRAM_ERR_CANT_PARSE {
            get {
                return ResourceManager.GetString("TELEGRAM_ERR_CANT_PARSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please start the bot before using this feature.
        /// </summary>
        internal static string TELEGRAM_EXCEPTION_NULL {
            get {
                return ResourceManager.GetString("TELEGRAM_EXCEPTION_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please start the bot before getting inventory.
        /// </summary>
        internal static string TELEGRAM_EXCEPTION_NULL_INVENTORY {
            get {
                return ResourceManager.GetString("TELEGRAM_EXCEPTION_NULL_INVENTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please enter here your barrel interval.
        ///Your current barrel interval: .
        /// </summary>
        internal static string TELEGRAM_INTERVAL_BARREL {
            get {
                return ResourceManager.GetString("TELEGRAM_INTERVAL_BARREL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please enter here your hibernation interval.
        ///Your current hibernation interval: .
        /// </summary>
        internal static string TELEGRAM_INTERVAL_HIBERNATION {
            get {
                return ResourceManager.GetString("TELEGRAM_INTERVAL_HIBERNATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please enter here your Iron limit.
        ///Your current limit on Iron: .
        /// </summary>
        internal static string TELEGRAM_INTERVAL_IRON {
            get {
                return ResourceManager.GetString("TELEGRAM_INTERVAL_IRON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please enter here your Stone limit.
        ///Your current limit on Stone: .
        /// </summary>
        internal static string TELEGRAM_INTERVAL_STONE {
            get {
                return ResourceManager.GetString("TELEGRAM_INTERVAL_STONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please enter here your Wood limit.
        ///Your current limit on Wood: .
        /// </summary>
        internal static string TELEGRAM_INTERVAL_WOOD {
            get {
                return ResourceManager.GetString("TELEGRAM_INTERVAL_WOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Starting....
        /// </summary>
        internal static string TELEGRAM_MSG_STARTING {
            get {
                return ResourceManager.GetString("TELEGRAM_MSG_STARTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stopped!.
        /// </summary>
        internal static string TELEGRAM_MSG_STOPPED {
            get {
                return ResourceManager.GetString("TELEGRAM_MSG_STOPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No telegram token.
        /// </summary>
        internal static string TELEGRAM_NO_TOKEN {
            get {
                return ResourceManager.GetString("TELEGRAM_NO_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Upgrade Factory only.
        /// </summary>
        internal static string TELEGRAM_SETTINGS_UPGRADE_FACTORY_ONLY {
            get {
                return ResourceManager.GetString("TELEGRAM_SETTINGS_UPGRADE_FACTORY_ONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Coins.
        /// </summary>
        internal static string TELEGRAM_SHIP_STRATEGY_MATERIAL_COINS {
            get {
                return ResourceManager.GetString("TELEGRAM_SHIP_STRATEGY_MATERIAL_COINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Fish.
        /// </summary>
        internal static string TELEGRAM_SHIP_STRATEGY_MATERIAL_FISH {
            get {
                return ResourceManager.GetString("TELEGRAM_SHIP_STRATEGY_MATERIAL_FISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Iron.
        /// </summary>
        internal static string TELEGRAM_SHIP_STRATEGY_MATERIAL_IRON {
            get {
                return ResourceManager.GetString("TELEGRAM_SHIP_STRATEGY_MATERIAL_IRON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Stone.
        /// </summary>
        internal static string TELEGRAM_SHIP_STRATEGY_MATERIAL_STONE {
            get {
                return ResourceManager.GetString("TELEGRAM_SHIP_STRATEGY_MATERIAL_STONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Wood.
        /// </summary>
        internal static string TELEGRAM_SHIP_STRATEGY_MATERIAL_WOOD {
            get {
                return ResourceManager.GetString("TELEGRAM_SHIP_STRATEGY_MATERIAL_WOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  More Loot.
        /// </summary>
        internal static string TELEGRAM_SHIP_STRATEGY_OPTIMAL_MORE_LOOT {
            get {
                return ResourceManager.GetString("TELEGRAM_SHIP_STRATEGY_OPTIMAL_MORE_LOOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Save Sailors.
        /// </summary>
        internal static string TELEGRAM_SHIP_STRATEGY_OPTIMAL_SAVE_SAILORS {
            get {
                return ResourceManager.GetString("TELEGRAM_SHIP_STRATEGY_OPTIMAL_SAVE_SAILORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Storage {0}/{1}.
        /// </summary>
        internal static string TELEGRAM_STORAGE {
            get {
                return ResourceManager.GetString("TELEGRAM_STORAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Auto-Barrel.
        /// </summary>
        internal static string TELEGRAM_STRATEGY_AUTO_BARREL {
            get {
                return ResourceManager.GetString("TELEGRAM_STRATEGY_AUTO_BARREL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Auto Ship.
        /// </summary>
        internal static string TELEGRAM_STRATEGY_AUTO_SHIP {
            get {
                return ResourceManager.GetString("TELEGRAM_STRATEGY_AUTO_SHIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Auto Upgrade.
        /// </summary>
        internal static string TELEGRAM_STRATEGY_AUTO_UPGRADE {
            get {
                return ResourceManager.GetString("TELEGRAM_STRATEGY_AUTO_UPGRADE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Collect Factory.
        /// </summary>
        internal static string TELEGRAM_STRATEGY_COLLECT_FACTORY {
            get {
                return ResourceManager.GetString("TELEGRAM_STRATEGY_COLLECT_FACTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Collect Fish.
        /// </summary>
        internal static string TELEGRAM_STRATEGY_COLLECT_FISH {
            get {
                return ResourceManager.GetString("TELEGRAM_STRATEGY_COLLECT_FISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Finish Upgrade.
        /// </summary>
        internal static string TELEGRAM_STRATEGY_FINISH_UPGRADE {
            get {
                return ResourceManager.GetString("TELEGRAM_STRATEGY_FINISH_UPGRADE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Produce Factory.
        /// </summary>
        internal static string TELEGRAM_STRATEGY_PRODUCE_FACTORY {
            get {
                return ResourceManager.GetString("TELEGRAM_STRATEGY_PRODUCE_FACTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Empty server_token
        ///Please fill server token in Settings tab.
        /// </summary>
        internal static string TOKEN_EMPTY {
            get {
                return ResourceManager.GetString("TOKEN_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [Current] Version: {0}.
        /// </summary>
        internal static string VERSION_CURRENT {
            get {
                return ResourceManager.GetString("VERSION_CURRENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [Old] Version: {0}.
        /// </summary>
        internal static string VERSION_OLD {
            get {
                return ResourceManager.GetString("VERSION_OLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A new update has been released, press OK to open download page!.
        /// </summary>
        internal static string VERSION_UPDATE_MBOX {
            get {
                return ResourceManager.GetString("VERSION_UPDATE_MBOX", resourceCulture);
            }
        }
    }
}
